<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class KotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['name' => 'Kota Banda Aceh', 'slug' => 'kota-banda-aceh', 'provinsi_id' => 1],
            ['name' => 'Kota Langsa', 'slug' => 'kota-langsa', 'provinsi_id' => 1],
            ['name' => 'Kota Lhokseumawe', 'slug' => 'kota-lhokseumawe', 'provinsi_id' => 1],
            ['name' => 'Kota Sabang', 'slug' => 'kota-sabang', 'provinsi_id' => 1],
            ['name' => 'Kabupaten Aceh Barat', 'slug' => 'kabupaten-aceh-barat', 'provinsi_id' => 1],
            ['name' => 'Kabupaten Aceh Barat Daya', 'slug' => 'kabupaten-aceh-barat-daya', 'provinsi_id' => 1],
            ['name' => 'Kabupaten Aceh Besar', 'slug' => 'kabupaten-aceh-besar', 'provinsi_id' => 1],
            ['name' => 'Kabupaten Aceh Jaya', 'slug' => 'kabupaten-aceh-jaya', 'provinsi_id' => 1],
            ['name' => 'Kabupaten Aceh Selatan', 'slug' => 'kabupaten-aceh-selatan', 'provinsi_id' => 1],
            ['name' => 'Kabupaten Aceh Singkil', 'slug' => 'kabupaten-aceh-singkil', 'provinsi_id' => 1],
            ['name' => 'Kabupaten Aceh Tamiang', 'slug' => 'kabupaten-aceh-tamiang', 'provinsi_id' => 1],
            ['name' => 'Kabupaten Aceh Tenggara', 'slug' => 'kabupaten-aceh-tenggara', 'provinsi_id' => 1],
            ['name' => 'Kabupaten Aceh Timur', 'slug' => 'kabupaten-aceh-timur', 'provinsi_id' => 1],
            ['name' => 'Kabupaten Bener Meriah', 'slug' => 'kabupaten-bener-meriah', 'provinsi_id' => 1],
            ['name' => 'Kabupaten Bireuen', 'slug' => 'kabupaten-bireuen', 'provinsi_id' => 1],
            ['name' => 'Kabupaten Gayo Lues', 'slug' => 'kabupaten-gayo-lues', 'provinsi_id' => 1],
            ['name' => 'Kabupaten Nagan Raya', 'slug' => 'kabupaten-nagan-raya', 'provinsi_id' => 1],
            ['name' => 'Kota Medan', 'slug' => 'kota-medan', 'provinsi_id' => 2],
            ['name' => 'Kota Binjai', 'slug' => 'kota-binjai', 'provinsi_id' => 2],
            ['name' => 'Kota Padang Sidempuan', 'slug' => 'kota-padang-sidempuan', 'provinsi_id' => 2],
            ['name' => 'Kota Pematang Siantar', 'slug' => 'kota-pematang-siantar', 'provinsi_id' => 2],
            ['name' => 'Kota Sibolga', 'slug' => 'kota-sibolga', 'provinsi_id' => 2],
            ['name' => 'Kota Tanjungbalai', 'slug' => 'kota-tanjungbalai', 'provinsi_id' => 2],
            ['name' => 'Kota Tebing Tinggi', 'slug' => 'kota-tebing-tinggi', 'provinsi_id' => 2],
            ['name' => 'Kota Gunungsitoli', 'slug' => 'kota-gunungsitoli', 'provinsi_id' => 2],
            ['name' => 'Kabupaten Asahan', 'slug' => 'kabupaten-asahan', 'provinsi_id' => 2],
            ['name' => 'Kabupaten Batu Bara', 'slug' => 'kabupaten-batu-bara', 'provinsi_id' => 2],
            ['name' => 'Kabupaten Dairi', 'slug' => 'kabupaten-dairi', 'provinsi_id' => 2],
            ['name' => 'Kabupaten Deli Serdang', 'slug' => 'kabupaten-deli-serdang', 'provinsi_id' => 2],
            ['name' => 'Kabupaten Humbang Hasundutan', 'slug' => 'kabupaten-humbang-hasundutan', 'provinsi_id' => 2],
            ['name' => 'Kabupaten Karo', 'slug' => 'kabupaten-karo', 'provinsi_id' => 2],
            ['name' => 'Kabupaten Labuhanbatu', 'slug' => 'kabupaten-labuhanbatu', 'provinsi_id' => 2],
            ['name' => 'Kabupaten Labuhanbatu Selatan', 'slug' => 'kabupaten-labuhanbatu-selatan', 'provinsi_id' => 2],
            ['name' => 'Kabupaten Labuhanbatu Utara', 'slug' => 'kabupaten-labuhanbatu-utara', 'provinsi_id' => 2],
            ['name' => 'Kabupaten Langkat', 'slug' => 'kabupaten-langkat', 'provinsi_id' => 2],
            ['name' => 'Kabupaten Mandailing Natal', 'slug' => 'kabupaten-mandailing-natal', 'provinsi_id' => 2],
            ['name' => 'Kabupaten Nias', 'slug' => 'kabupaten-nias', 'provinsi_id' => 2],
            ['name' => 'Kabupaten Nias Barat', 'slug' => 'kabupaten-nias-barat', 'provinsi_id' => 2],
            ['name' => 'Kabupaten Nias Selatan', 'slug' => 'kabupaten-nias-selatan', 'provinsi_id' => 2],
            ['name' => 'Kabupaten Nias Utara', 'slug' => 'kabupaten-nias-utara', 'provinsi_id' => 2],
            ['name' => 'Kabupaten Padang Lawas', 'slug' => 'kabupaten-padang-lawas', 'provinsi_id' => 2],
            ['name' => 'Kabupaten Padang Lawas Utara', 'slug' => 'kabupaten-padang-lawas-utara', 'provinsi_id' => 2],
            ['name' => 'Kabupaten Pakpak Bharat', 'slug' => 'kabupaten-pakpak-bharat', 'provinsi_id' => 2],
            ['name' => 'Kabupaten Samosir', 'slug' => 'kabupaten-samosir', 'provinsi_id' => 2],
            ['name' => 'Kabupaten Serdang Bedagai', 'slug' => 'kabupaten-serdang-bedagai', 'provinsi_id' => 2],
            ['name' => 'Kabupaten Simalungun', 'slug' => 'kabupaten-simalungun', 'provinsi_id' => 2],
            ['name' => 'Kabupaten Tapanuli Selatan', 'slug' => 'kabupaten-tapanuli-selatan', 'provinsi_id' => 2],
            ['name' => 'Kabupaten Tapanuli Tengah', 'slug' => 'kabupaten-tapanuli-tengah', 'provinsi_id' => 2],
            ['name' => 'Kabupaten Tapanuli Utara', 'slug' => 'kabupaten-tapanuli-utara', 'provinsi_id' => 2],
            ['name' => 'Kabupaten Toba', 'slug' => 'kabupaten-toba', 'provinsi_id' => 2],
            ['name' => 'Kota Padang', 'slug' => 'kota-padang', 'provinsi_id' => 3],
            ['name' => 'Kota Solok', 'slug' => 'kota-solok', 'provinsi_id' => 3],
            ['name' => 'Kota Sawahlunto', 'slug' => 'kota-sawahlunto', 'provinsi_id' => 3],
            ['name' => 'Kota Padang Panjang', 'slug' => 'kota-padang-panjang', 'provinsi_id' => 3],
            ['name' => 'Kota Bukittinggi', 'slug' => 'kota-bukittinggi', 'provinsi_id' => 3],
            ['name' => 'Kota Payakumbuh', 'slug' => 'kota-payakumbuh', 'provinsi_id' => 3],
            ['name' => 'Kota Pariaman', 'slug' => 'kota-pariaman', 'provinsi_id' => 3],
            ['name' => 'Kabupaten Agam', 'slug' => 'kabupaten-agam', 'provinsi_id' => 3],
            ['name' => 'Kabupaten Dharmasraya', 'slug' => 'kabupaten-dharmasraya', 'provinsi_id' => 3],
            ['name' => 'Kabupaten Kepulauan Mentawai', 'slug' => 'kabupaten-kepulauan-mentawai', 'provinsi_id' => 3],
            ['name' => 'Kabupaten Lima Puluh Kota', 'slug' => 'kabupaten-lima-puluh-kota', 'provinsi_id' => 3],
            ['name' => 'Kabupaten Padang Pariaman', 'slug' => 'kabupaten-padang-pariaman', 'provinsi_id' => 3],
            ['name' => 'Kabupaten Pasaman', 'slug' => 'kabupaten-pasaman', 'provinsi_id' => 3],
            ['name' => 'Kabupaten Pasaman Barat', 'slug' => 'kabupaten-pasaman-barat', 'provinsi_id' => 3],
            ['name' => 'Kabupaten Pesisir Selatan', 'slug' => 'kabupaten-pesisir-selatan', 'provinsi_id' => 3],
            ['name' => 'Kabupaten Sijunjung', 'slug' => 'kabupaten-sijunjung', 'provinsi_id' => 3],
            ['name' => 'Kabupaten Solok', 'slug' => 'kabupaten-solok', 'provinsi_id' => 3],
            ['name' => 'Kabupaten Solok Selatan', 'slug' => 'kabupaten-solok-selatan', 'provinsi_id' => 3],
            ['name' => 'Kabupaten Tanah Datar', 'slug' => 'kabupaten-tanah-datar', 'provinsi_id' => 3],
            ['name' => 'Kota Pekanbaru', 'slug' => 'kota-pekanbaru', 'provinsi_id' => 4],
            ['name' => 'Kota Dumai', 'slug' => 'kota-dumai', 'provinsi_id' => 4],
            ['name' => 'Kabupaten Bengkalis', 'slug' => 'kabupaten-bengkalis', 'provinsi_id' => 4],
            ['name' => 'Kabupaten Indragiri Hulu', 'slug' => 'kabupaten-indragiri-hulu', 'provinsi_id' => 4],
            ['name' => 'Kabupaten Indragiri Hilir', 'slug' => 'kabupaten-indragiri-hilir', 'provinsi_id' => 4],
            ['name' => 'Kabupaten Kampar', 'slug' => 'kabupaten-kampar', 'provinsi_id' => 4],
            ['name' => 'Kabupaten Kepulauan Meranti', 'slug' => 'kabupaten-kepulauan-meranti', 'provinsi_id' => 4],
            ['name' => 'Kabupaten Kuantan Singingi', 'slug' => 'kabupaten-kuantan-singingi', 'provinsi_id' => 4],
            ['name' => 'Kabupaten Pelalawan', 'slug' => 'kabupaten-pelalawan', 'provinsi_id' => 4],
            ['name' => 'Kabupaten Rokan Hilir', 'slug' => 'kabupaten-rokan-hilir', 'provinsi_id' => 4],
            ['name' => 'Kabupaten Rokan Hulu', 'slug' => 'kabupaten-rokan-hulu', 'provinsi_id' => 4],
            ['name' => 'Kabupaten Siak', 'slug' => 'kabupaten-siak', 'provinsi_id' => 4],
            ['name' => 'Kota Jambi', 'slug' => 'kota-jambi', 'provinsi_id' => 5],
            ['name' => 'Kota Sungai Penuh', 'slug' => 'kota-sungai-penuh', 'provinsi_id' => 5],
            ['name' => 'Kabupaten Batanghari', 'slug' => 'kabupaten-batanghari', 'provinsi_id' => 5],
            ['name' => 'Kabupaten Bungo', 'slug' => 'kabupaten-bungo', 'provinsi_id' => 5],
            ['name' => 'Kabupaten Kerinci', 'slug' => 'kabupaten-kerinci', 'provinsi_id' => 5],
            ['name' => 'Kabupaten Merangin', 'slug' => 'kabupaten-merangin', 'provinsi_id' => 5],
            ['name' => 'Kabupaten Muaro Jambi', 'slug' => 'kabupaten-muaro-jambi', 'provinsi_id' => 5],
            ['name' => 'Kabupaten Sarolangun', 'slug' => 'kabupaten-sarolangun', 'provinsi_id' => 5],
            ['name' => 'Kabupaten Tanjung Jabung Barat', 'slug' => 'kabupaten-tanjung-jabung-barat', 'provinsi_id' => 5],
            ['name' => 'Kabupaten Tanjung Jabung Timur', 'slug' => 'kabupaten-tanjung-jabung-timur', 'provinsi_id' => 5],
            ['name' => 'Kabupaten Tebo', 'slug' => 'kabupaten-tebo', 'provinsi_id' => 5],
            ['name' => 'Kota Palembang', 'slug' => 'kota-palembang', 'provinsi_id' => 6],
            ['name' => 'Kota Pagar Alam', 'slug' => 'kota-pagar-alam', 'provinsi_id' => 6],
            ['name' => 'Kota Lubuklinggau', 'slug' => 'kota-lubuklinggau', 'provinsi_id' => 6],
            ['name' => 'Kota Prabumulih', 'slug' => 'kota-prabumulih', 'provinsi_id' => 6],
            ['name' => 'Kabupaten Banyuasin', 'slug' => 'kabupaten-banyuasin', 'provinsi_id' => 6],
            ['name' => 'Kabupaten Empat Lawang', 'slug' => 'kabupaten-empat-lawang', 'provinsi_id' => 6],
            ['name' => 'Kabupaten Lahat', 'slug' => 'kabupaten-lahat', 'provinsi_id' => 6],
            ['name' => 'Kabupaten Muara Enim', 'slug' => 'kabupaten-muara-enim', 'provinsi_id' => 6],
            ['name' => 'Kabupaten Musi Banyuasin', 'slug' => 'kabupaten-musi-banyuasin', 'provinsi_id' => 6],
            ['name' => 'Kabupaten Musi Rawas', 'slug' => 'kabupaten-musi-rawas', 'provinsi_id' => 6],
            ['name' => 'Kabupaten Musi Rawas Utara', 'slug' => 'kabupaten-musi-rawas-utara', 'provinsi_id' => 6],
            ['name' => 'Kabupaten Ogan Ilir', 'slug' => 'kabupaten-ogan-ilir', 'provinsi_id' => 6],
            ['name' => 'Kabupaten Ogan Komering Ilir', 'slug' => 'kabupaten-ogan-komering-ilir', 'provinsi_id' => 6],
            ['name' => 'Kabupaten Ogan Komering Ulu', 'slug' => 'kabupaten-ogan-komering-ulu', 'provinsi_id' => 6],
            ['name' => 'Kabupaten Ogan Komering Ulu Selatan', 'slug' => 'kabupaten-ogan-komering-ulu-selatan', 'provinsi_id' => 6],
            ['name' => 'Kabupaten Ogan Komering Ulu Timur', 'slug' => 'kabupaten-ogan-komering-ulu-timur', 'provinsi_id' => 6],
            ['name' => 'Kabupaten Penukal Abab Lematang Ilir', 'slug' => 'kabupaten-penukal-abab-lematang-ilir', 'provinsi_id' => 6],
            ['name' => 'Kota Bengkulu', 'slug' => 'kota-bengkulu', 'provinsi_id' => 7],
            ['name' => 'Kabupaten Bengkulu Selatan', 'slug' => 'kabupaten-bengkulu-selatan', 'provinsi_id' => 7],
            ['name' => 'Kabupaten Bengkulu Tengah', 'slug' => 'kabupaten-bengkulu-tengah', 'provinsi_id' => 7],
            ['name' => 'Kabupaten Bengkulu Utara', 'slug' => 'kabupaten-bengkulu-utara', 'provinsi_id' => 7],
            ['name' => 'Kabupaten Kaur', 'slug' => 'kabupaten-kaur', 'provinsi_id' => 7],
            ['name' => 'Kabupaten Kepahiang', 'slug' => 'kabupaten-kepahiang', 'provinsi_id' => 7],
            ['name' => 'Kabupaten Lebong', 'slug' => 'kabupaten-lebong', 'provinsi_id' => 7],
            ['name' => 'Kabupaten Mukomuko', 'slug' => 'kabupaten-mukomuko', 'provinsi_id' => 7],
            ['name' => 'Kabupaten Rejang Lebong', 'slug' => 'kabupaten-rejang-lebong', 'provinsi_id' => 7],
            ['name' => 'Kabupaten Seluma', 'slug' => 'kabupaten-seluma', 'provinsi_id' => 7],
            ['name' => 'Kota Bandar Lampung', 'slug' => 'kota-bandar-lampung', 'provinsi_id' => 8],
            ['name' => 'Kota Metro', 'slug' => 'kota-metro', 'provinsi_id' => 8],
            ['name' => 'Kabupaten Lampung Barat', 'slug' => 'kabupaten-lampung-barat', 'provinsi_id' => 8],
            ['name' => 'Kabupaten Lampung Selatan', 'slug' => 'kabupaten-lampung-selatan', 'provinsi_id' => 8],
            ['name' => 'Kabupaten Lampung Tengah', 'slug' => 'kabupaten-lampung-tengah', 'provinsi_id' => 8],
            ['name' => 'Kabupaten Lampung Timur', 'slug' => 'kabupaten-lampung-timur', 'provinsi_id' => 8],
            ['name' => 'Kabupaten Lampung Utara', 'slug' => 'kabupaten-lampung-utara', 'provinsi_id' => 8],
            ['name' => 'Kabupaten Mesuji', 'slug' => 'kabupaten-mesuji', 'provinsi_id' => 8],
            ['name' => 'Kabupaten Pesawaran', 'slug' => 'kabupaten-pesawaran', 'provinsi_id' => 8],
            ['name' => 'Kabupaten Pesisir Barat', 'slug' => 'kabupaten-pesisir-barat', 'provinsi_id' => 8],
            ['name' => 'Kabupaten Pringsewu', 'slug' => 'kabupaten-pringsewu', 'provinsi_id' => 8],
            ['name' => 'Kabupaten Tanggamus', 'slug' => 'kabupaten-tanggamus', 'provinsi_id' => 8],
            ['name' => 'Kabupaten Tulang Bawang', 'slug' => 'kabupaten-tulang-bawang', 'provinsi_id' => 8],
            ['name' => 'Kabupaten Tulang Bawang Barat', 'slug' => 'kabupaten-tulang-bawang-barat', 'provinsi_id' => 8],
            ['name' => 'Kabupaten Way Kanan', 'slug' => 'kabupaten-way-kanan', 'provinsi_id' => 8],
            ['name' => 'Kota Pangkalpinang', 'slug' => 'kota-pangkalpinang', 'provinsi_id' => 9],
            ['name' => 'Kabupaten Bangka', 'slug' => 'kabupaten-bangka', 'provinsi_id' => 9],
            ['name' => 'Kabupaten Bangka Barat', 'slug' => 'kabupaten-bangka-barat', 'provinsi_id' => 9],
            ['name' => 'Kabupaten Bangka Selatan', 'slug' => 'kabupaten-bangka-selatan', 'provinsi_id' => 9],
            ['name' => 'Kabupaten Bangka Tengah', 'slug' => 'kabupaten-bangka-tengah', 'provinsi_id' => 9],
            ['name' => 'Kabupaten Belitung', 'slug' => 'kabupaten-belitung', 'provinsi_id' => 9],
            ['name' => 'Kabupaten Belitung Timur', 'slug' => 'kabupaten-belitung-timur', 'provinsi_id' => 9],
            ['name' => 'Kota Batam', 'slug' => 'kota-batam', 'provinsi_id' => 10],
            ['name' => 'Kota Tanjungpinang', 'slug' => 'kota-tanjungpinang', 'provinsi_id' => 10],
            ['name' => 'Kabupaten Bintan', 'slug' => 'kabupaten-bintan', 'provinsi_id' => 10],
            ['name' => 'Kabupaten Karimun', 'slug' => 'kabupaten-karimun', 'provinsi_id' => 10],
            ['name' => 'Kabupaten Lingga', 'slug' => 'kabupaten-lingga', 'provinsi_id' => 10],
            ['name' => 'Kabupaten Kepulauan Anambas', 'slug' => 'kabupaten-kepulauan-anambas', 'provinsi_id' => 10],
            ['name' => 'Kabupaten Natuna', 'slug' => 'kabupaten-natuna', 'provinsi_id' => 10],
            ['name' => 'Kota Jakarta Barat', 'slug' => 'kota-jakarta-barat', 'provinsi_id' => 11],
            ['name' => 'Kota Jakarta Pusat', 'slug' => 'kota-jakarta-pusat', 'provinsi_id' => 11],
            ['name' => 'Kota Jakarta Selatan', 'slug' => 'kota-jakarta-selatan', 'provinsi_id' => 11],
            ['name' => 'Kota Jakarta Timur', 'slug' => 'kota-jakarta-timur', 'provinsi_id' => 11],
            ['name' => 'Kota Jakarta Utara', 'slug' => 'kota-jakarta-utara', 'provinsi_id' => 11],
            ['name' => 'Kabupaten Kepulauan Seribu', 'slug' => 'kabupaten-kepulauan-seribu', 'provinsi_id' => 11],
            ['name' => 'Kota Bandung', 'slug' => 'kota-bandung', 'provinsi_id' => 12],
            ['name' => 'Kota Banjar', 'slug' => 'kota-banjar', 'provinsi_id' => 12],
            ['name' => 'Kota Bekasi', 'slug' => 'kota-bekasi', 'provinsi_id' => 12],
            ['name' => 'Kota Bogor', 'slug' => 'kota-bogor', 'provinsi_id' => 12],
            ['name' => 'Kota Cimahi', 'slug' => 'kota-cimahi', 'provinsi_id' => 12],
            ['name' => 'Kota Cirebon', 'slug' => 'kota-cirebon', 'provinsi_id' => 12],
            ['name' => 'Kota Sukabumi', 'slug' => 'kota-sukabumi', 'provinsi_id' => 12],
            ['name' => 'Kota Tasikmalaya', 'slug' => 'kota-tasikmalaya', 'provinsi_id' => 12],
            ['name' => 'Kota Depok', 'slug' => 'kota-depok', 'provinsi_id' => 12],
            ['name' => 'Kabupaten Bandung', 'slug' => 'kabupaten-bandung', 'provinsi_id' => 12],
            ['name' => 'Kabupaten Bandung Barat', 'slug' => 'kabupaten-bandung-barat', 'provinsi_id' => 12],
            ['name' => 'Kabupaten Bekasi', 'slug' => 'kabupaten-bekasi', 'provinsi_id' => 12],
            ['name' => 'Kabupaten Bogor', 'slug' => 'kabupaten-bogor', 'provinsi_id' => 12],
            ['name' => 'Kabupaten Ciamis', 'slug' => 'kabupaten-ciamis', 'provinsi_id' => 12],
            ['name' => 'Kabupaten Cianjur', 'slug' => 'kabupaten-cianjur', 'provinsi_id' => 12],
            ['name' => 'Kabupaten Cirebon', 'slug' => 'kabupaten-cirebon', 'provinsi_id' => 12],
            ['name' => 'Kabupaten Garut', 'slug' => 'kabupaten-garut', 'provinsi_id' => 12],
            ['name' => 'Kabupaten Indramayu', 'slug' => 'kabupaten-indramayu', 'provinsi_id' => 12],
            ['name' => 'Kabupaten Karawang', 'slug' => 'kabupaten-karawang', 'provinsi_id' => 12],
            ['name' => 'Kabupaten Kuningan', 'slug' => 'kabupaten-kuningan', 'provinsi_id' => 12],
            ['name' => 'Kabupaten Majalengka', 'slug' => 'kabupaten-majalengka', 'provinsi_id' => 12],
            ['name' => 'Kabupaten Pangandaran', 'slug' => 'kabupaten-pangandaran', 'provinsi_id' => 12],
            ['name' => 'Kabupaten Purwakarta', 'slug' => 'kabupaten-purwakarta', 'provinsi_id' => 12],
            ['name' => 'Kabupaten Subang', 'slug' => 'kabupaten-subang', 'provinsi_id' => 12],
            ['name' => 'Kabupaten Sukabumi', 'slug' => 'kabupaten-sukabumi', 'provinsi_id' => 12],
            ['name' => 'Kabupaten Sumedang', 'slug' => 'kabupaten-sumedang', 'provinsi_id' => 12],
            ['name' => 'Kabupaten Tasikmalaya', 'slug' => 'kabupaten-tasikmalaya', 'provinsi_id' => 12],
            ['name' => 'Kota Semarang', 'slug' => 'kota-semarang', 'provinsi_id' => 13],
            ['name' => 'Kota Surakarta (Solo)', 'slug' => 'kota-surakarta', 'provinsi_id' => 13],
            ['name' => 'Kota Magelang', 'slug' => 'kota-magelang', 'provinsi_id' => 13],
            ['name' => 'Kota Tegal', 'slug' => 'kota-tegal', 'provinsi_id' => 13],
            ['name' => 'Kota Pekalongan', 'slug' => 'kota-pekalongan', 'provinsi_id' => 13],
            ['name' => 'Kota Salatiga', 'slug' => 'kota-salatiga', 'provinsi_id' => 13],
            ['name' => 'Kota Kendal', 'slug' => 'kota-kendal', 'provinsi_id' => 13],
            ['name' => 'Kota Pemalang', 'slug' => 'kota-pemalang', 'provinsi_id' => 13],
            ['name' => 'Kota Brebes', 'slug' => 'kota-brebes', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Banyumas', 'slug' => 'kabupaten-banyumas', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Cilacap', 'slug' => 'kabupaten-cilacap', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Purbalingga', 'slug' => 'kabupaten-purbalingga', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Banjarnegara', 'slug' => 'kabupaten-banjarnegara', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Kebumen', 'slug' => 'kabupaten-kebumen', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Purworejo', 'slug' => 'kabupaten-purworejo', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Wonosobo', 'slug' => 'kabupaten-wonosobo', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Magelang', 'slug' => 'kabupaten-magelang', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Boyolali', 'slug' => 'kabupaten-boyolali', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Klaten', 'slug' => 'kabupaten-klaten', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Sukoharjo', 'slug' => 'kabupaten-sukoharjo', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Wonogiri', 'slug' => 'kabupaten-wonogiri', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Karanganyar', 'slug' => 'kabupaten-karanganyar', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Sragen', 'slug' => 'kabupaten-sragen', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Grobogan', 'slug' => 'kabupaten-grobogan', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Blora', 'slug' => 'kabupaten-blora', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Rembang', 'slug' => 'kabupaten-rembang', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Pati', 'slug' => 'kabupaten-pati', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Kudus', 'slug' => 'kabupaten-kudus', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Jepara', 'slug' => 'kabupaten-jepara', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Demak', 'slug' => 'kabupaten-demak', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Temanggung', 'slug' => 'kabupaten-temanggung', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Kendal', 'slug' => 'kabupaten-kendal', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Batang', 'slug' => 'kabupaten-batang', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Pekalongan', 'slug' => 'kabupaten-pekalongan', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Pemalang', 'slug' => 'kabupaten-pemalang', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Tegal', 'slug' => 'kabupaten-tegal', 'provinsi_id' => 13],
            ['name' => 'Kabupaten Brebes', 'slug' => 'kabupaten-brebes', 'provinsi_id' => 13],
            ['name' => 'Kota Yogyakarta', 'slug' => 'kota-yogyakarta', 'provinsi_id' => 14],
            ['name' => 'Kabupaten Bantul', 'slug' => 'kabupaten-bantul', 'provinsi_id' => 14],
            ['name' => 'Kabupaten Sleman', 'slug' => 'kabupaten-sleman', 'provinsi_id' => 14],
            ['name' => 'Kabupaten Kulon Progo', 'slug' => 'kabupaten-kulon-progo', 'provinsi_id' => 14],
            ['name' => 'Kabupaten Gunung Kidul', 'slug' => 'kabupaten-gunung-kidul', 'provinsi_id' => 14],
            ['name' => 'Kota Surabaya', 'slug' => 'kota-surabaya', 'provinsi_id' => 15],
            ['name' => 'Kota Malang', 'slug' => 'kota-malang', 'provinsi_id' => 15],
            ['name' => 'Kota Batu', 'slug' => 'kota-batu', 'provinsi_id' => 15],
            ['name' => 'Kota Pasuruan', 'slug' => 'kota-pasuruan', 'provinsi_id' => 15],
            ['name' => 'Kota Probolinggo', 'slug' => 'kota-probolinggo', 'provinsi_id' => 15],
            ['name' => 'Kota Madiun', 'slug' => 'kota-madiun', 'provinsi_id' => 15],
            ['name' => 'Kota Mojokerto', 'slug' => 'kota-mojokerto', 'provinsi_id' => 15],
            ['name' => 'Kota Kediri', 'slug' => 'kota-kediri', 'provinsi_id' => 15],
            ['name' => 'Kota Blitar', 'slug' => 'kota-blitar', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Bangkalan', 'slug' => 'kabupaten-bangkalan', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Banyuwangi', 'slug' => 'kabupaten-banyuwangi', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Blitar', 'slug' => 'kabupaten-blitar', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Bojonegoro', 'slug' => 'kabupaten-bojonegoro', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Bondowoso', 'slug' => 'kabupaten-bondowoso', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Gresik', 'slug' => 'kabupaten-gresik', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Jember', 'slug' => 'kabupaten-jember', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Jombang', 'slug' => 'kabupaten-jombang', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Kediri', 'slug' => 'kabupaten-kediri', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Lamongan', 'slug' => 'kabupaten-lamongan', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Lumajang', 'slug' => 'kabupaten-lumajang', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Madiun', 'slug' => 'kabupaten-madiun', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Magetan', 'slug' => 'kabupaten-magetan', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Malang', 'slug' => 'kabupaten-malang', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Mojokerto', 'slug' => 'kabupaten-mojokerto', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Nganjuk', 'slug' => 'kabupaten-nganjuk', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Ngawi', 'slug' => 'kabupaten-ngawi', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Pacitan', 'slug' => 'kabupaten-pacitan', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Pamekasan', 'slug' => 'kabupaten-pamekasan', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Pasuruan', 'slug' => 'kabupaten-pasuruan', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Ponorogo', 'slug' => 'kabupaten-ponorogo', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Probolinggo', 'slug' => 'kabupaten-probolinggo', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Sampang', 'slug' => 'kabupaten-sampang', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Sidoarjo', 'slug' => 'kabupaten-sidoarjo', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Situbondo', 'slug' => 'kabupaten-situbondo', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Sumenep', 'slug' => 'kabupaten-sumenep', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Trenggalek', 'slug' => 'kabupaten-trenggalek', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Tuban', 'slug' => 'kabupaten-tuban', 'provinsi_id' => 15],
            ['name' => 'Kabupaten Tulungagung', 'slug' => 'kabupaten-tulungagung', 'provinsi_id' => 15],
            ['name' => 'Kota Serang', 'slug' => 'kota-serang', 'provinsi_id' => 16],
            ['name' => 'Kota Cilegon', 'slug' => 'kota-cilegon', 'provinsi_id' => 16],
            ['name' => 'Kota Tangerang', 'slug' => 'kota-tangerang', 'provinsi_id' => 16],
            ['name' => 'Kota Tangerang Selatan', 'slug' => 'kota-tangerang-selatan', 'provinsi_id' => 16],
            ['name' => 'Kabupaten Lebak', 'slug' => 'kabupaten-lebak', 'provinsi_id' => 16],
            ['name' => 'Kabupaten Pandeglang', 'slug' => 'kabupaten-pandeglang', 'provinsi_id' => 16],
            ['name' => 'Kabupaten Serang', 'slug' => 'kabupaten-serang', 'provinsi_id' => 16],
            ['name' => 'Kabupaten Tangerang', 'slug' => 'kabupaten-tangerang', 'provinsi_id' => 16],
            ['name' => 'Kota Denpasar', 'slug' => 'kota-denpasar', 'provinsi_id' => 17],
            ['name' => 'Kabupaten Badung', 'slug' => 'kabupaten-badung', 'provinsi_id' => 17],
            ['name' => 'Kabupaten Bangli', 'slug' => 'kabupaten-bangli', 'provinsi_id' => 17],
            ['name' => 'Kabupaten Buleleng', 'slug' => 'kabupaten-buleleng', 'provinsi_id' => 17],
            ['name' => 'Kabupaten Gianyar', 'slug' => 'kabupaten-gianyar', 'provinsi_id' => 17],
            ['name' => 'Kabupaten Jembrana', 'slug' => 'kabupaten-jembrana', 'provinsi_id' => 17],
            ['name' => 'Kabupaten Karangasem', 'slug' => 'kabupaten-karangasem', 'provinsi_id' => 17],
            ['name' => 'Kabupaten Klungkung', 'slug' => 'kabupaten-klungkung', 'provinsi_id' => 17],
            ['name' => 'Kabupaten Tabanan', 'slug' => 'kabupaten-tabanan', 'provinsi_id' => 17],
            ['name' => 'Kota Mataram', 'slug' => 'kota-mataram', 'provinsi_id' => 18],
            ['name' => 'Kota Bima', 'slug' => 'kota-bima', 'provinsi_id' => 18],
            ['name' => 'Kabupaten Bima', 'slug' => 'kabupaten-bima', 'provinsi_id' => 18],
            ['name' => 'Kabupaten Dompu', 'slug' => 'kabupaten-dompu', 'provinsi_id' => 18],
            ['name' => 'Kabupaten Lombok Barat', 'slug' => 'kabupaten-lombok-barat', 'provinsi_id' => 18],
            ['name' => 'Kabupaten Lombok Tengah', 'slug' => 'kabupaten-lombok-tengah', 'provinsi_id' => 18],
            ['name' => 'Kabupaten Lombok Timur', 'slug' => 'kabupaten-lombok-timur', 'provinsi_id' => 18],
            ['name' => 'Kabupaten Lombok Utara', 'slug' => 'kabupaten-lombok-utara', 'provinsi_id' => 18],
            ['name' => 'Kabupaten Sumbawa', 'slug' => 'kabupaten-sumbawa', 'provinsi_id' => 18],
            ['name' => 'Kabupaten Sumbawa Barat', 'slug' => 'kabupaten-sumbawa-barat', 'provinsi_id' => 18],
            ['name' => 'Kota Kupang', 'slug' => 'kota-kupang', 'provinsi_id' => 19],
            ['name' => 'Kabupaten Alor', 'slug' => 'kabupaten-alor', 'provinsi_id' => 19],
            ['name' => 'Kabupaten Belu', 'slug' => 'kabupaten-belu', 'provinsi_id' => 19],
            ['name' => 'Kabupaten Ende', 'slug' => 'kabupaten-ende', 'provinsi_id' => 19],
            ['name' => 'Kabupaten Flores Timur', 'slug' => 'kabupaten-flores-timur', 'provinsi_id' => 19],
            ['name' => 'Kabupaten Kupang', 'slug' => 'kabupaten-kupang', 'provinsi_id' => 19],
            ['name' => 'Kabupaten Lembata', 'slug' => 'kabupaten-lembata', 'provinsi_id' => 19],
            ['name' => 'Kabupaten Malaka', 'slug' => 'kabupaten-malaka', 'provinsi_id' => 19],
            ['name' => 'Kabupaten Manggarai', 'slug' => 'kabupaten-manggarai', 'provinsi_id' => 19],
            ['name' => 'Kabupaten Manggarai Barat', 'slug' => 'kabupaten-manggarai-barat', 'provinsi_id' => 19],
            ['name' => 'Kabupaten Manggarai Timur', 'slug' => 'kabupaten-manggarai-timur', 'provinsi_id' => 19],
            ['name' => 'Kabupaten Nagekeo', 'slug' => 'kabupaten-nagekeo', 'provinsi_id' => 19],
            ['name' => 'Kabupaten Ngada', 'slug' => 'kabupaten-ngada', 'provinsi_id' => 19],
            ['name' => 'Kabupaten Rote Ndao', 'slug' => 'kabupaten-rote-ndao', 'provinsi_id' => 19],
            ['name' => 'Kabupaten Sabu Raijua', 'slug' => 'kabupaten-sabu-raijua', 'provinsi_id' => 19],
            ['name' => 'Kabupaten Sikka', 'slug' => 'kabupaten-sikka', 'provinsi_id' => 19],
            ['name' => 'Kabupaten Sumba Barat', 'slug' => 'kabupaten-sumba-barat', 'provinsi_id' => 19],
            ['name' => 'Kabupaten Sumba Barat Daya', 'slug' => 'kabupaten-sumba-barat-daya', 'provinsi_id' => 19],
            ['name' => 'Kabupaten Sumba Tengah', 'slug' => 'kabupaten-sumba-tengah', 'provinsi_id' => 19],
            ['name' => 'Kabupaten Sumba Timur', 'slug' => 'kabupaten-sumba-timur', 'provinsi_id' => 19],
            ['name' => 'Kabupaten Timor Tengah Selatan', 'slug' => 'kabupaten-timor-tengah-selatan', 'provinsi_id' => 19],
            ['name' => 'Kabupaten Timor Tengah Utara', 'slug' => 'kabupaten-timor-tengah-utara', 'provinsi_id' => 19],
            ['name' => 'Kota Pontianak', 'slug' => 'kota-pontianak', 'provinsi_id' => 20],
            ['name' => 'Kota Singkawang', 'slug' => 'kota-singkawang', 'provinsi_id' => 20],
            ['name' => 'Kabupaten Bengkayang', 'slug' => 'kabupaten-bengkayang', 'provinsi_id' => 20],
            ['name' => 'Kabupaten Kapuas Hulu', 'slug' => 'kabupaten-kapuas-hulu', 'provinsi_id' => 20],
            ['name' => 'Kabupaten Kayong Utara', 'slug' => 'kabupaten-kayong-utara', 'provinsi_id' => 20],
            ['name' => 'Kabupaten Ketapang', 'slug' => 'kabupaten-ketapang', 'provinsi_id' => 20],
            ['name' => 'Kabupaten Kubu Raya', 'slug' => 'kabupaten-kubu-raya', 'provinsi_id' => 20],
            ['name' => 'Kabupaten Landak', 'slug' => 'kabupaten-landak', 'provinsi_id' => 20],
            ['name' => 'Kabupaten Melawi', 'slug' => 'kabupaten-melawi', 'provinsi_id' => 20],
            ['name' => 'Kabupaten Mempawah', 'slug' => 'kabupaten-mempawah', 'provinsi_id' => 20],
            ['name' => 'Kabupaten Sambas', 'slug' => 'kabupaten-sambas', 'provinsi_id' => 20],
            ['name' => 'Kabupaten Sanggau', 'slug' => 'kabupaten-sanggau', 'provinsi_id' => 20],
            ['name' => 'Kabupaten Sekadau', 'slug' => 'kabupaten-sekadau', 'provinsi_id' => 20],
            ['name' => 'Kabupaten Sintang', 'slug' => 'kabupaten-sintang', 'provinsi_id' => 20],
            ['name' => 'Kota Banjarmasin', 'slug' => 'kota-banjarmasin', 'provinsi_id' => 21],
            ['name' => 'Kota Banjarbaru', 'slug' => 'kota-banjarbaru', 'provinsi_id' => 21],
            ['name' => 'Kabupaten Balangan', 'slug' => 'kabupaten-balangan', 'provinsi_id' => 21],
            ['name' => 'Kabupaten Banjar', 'slug' => 'kabupaten-banjar', 'provinsi_id' => 21],
            ['name' => 'Kabupaten Barito Kuala', 'slug' => 'kabupaten-barito-kuala', 'provinsi_id' => 21],
            ['name' => 'Kabupaten Hulu Sungai Selatan', 'slug' => 'kabupaten-hulu-sungai-selatan', 'provinsi_id' => 21],
            ['name' => 'Kabupaten Hulu Sungai Tengah', 'slug' => 'kabupaten-hulu-sungai-tengah', 'provinsi_id' => 21],
            ['name' => 'Kabupaten Hulu Sungai Utara', 'slug' => 'kabupaten-hulu-sungai-utara', 'provinsi_id' => 21],
            ['name' => 'Kabupaten Kotabaru', 'slug' => 'kabupaten-kotabaru', 'provinsi_id' => 21],
            ['name' => 'Kabupaten Tabalong', 'slug' => 'kabupaten-tabalong', 'provinsi_id' => 21],
            ['name' => 'Kabupaten Tanah Bumbu', 'slug' => 'kabupaten-tanah-bumbu', 'provinsi_id' => 21],
            ['name' => 'Kabupaten Tanah Laut', 'slug' => 'kabupaten-tanah-laut', 'provinsi_id' => 21],
            ['name' => 'Kabupaten Tapin', 'slug' => 'kabupaten-tapin', 'provinsi_id' => 21],
            ['name' => 'Kota Palangka Raya', 'slug' => 'kota-palangka-raya', 'provinsi_id' => 22],
            ['name' => 'Kabupaten Barito Selatan', 'slug' => 'kabupaten-barito-selatan', 'provinsi_id' => 22],
            ['name' => 'Kabupaten Barito Timur', 'slug' => 'kabupaten-barito-timur', 'provinsi_id' => 22],
            ['name' => 'Kabupaten Barito Utara', 'slug' => 'kabupaten-barito-utara', 'provinsi_id' => 22],
            ['name' => 'Kabupaten Gunung Mas', 'slug' => 'kabupaten-gunung-mas', 'provinsi_id' => 22],
            ['name' => 'Kabupaten Kapuas', 'slug' => 'kabupaten-kapuas', 'provinsi_id' => 22],
            ['name' => 'Kabupaten Katingan', 'slug' => 'kabupaten-katingan', 'provinsi_id' => 22],
            ['name' => 'Kabupaten Kotawaringin Barat', 'slug' => 'kabupaten-kotawaringin-barat', 'provinsi_id' => 22],
            ['name' => 'Kabupaten Kotawaringin Timur', 'slug' => 'kabupaten-kotawaringin-timur', 'provinsi_id' => 22],
            ['name' => 'Kabupaten Lamandau', 'slug' => 'kabupaten-lamandau', 'provinsi_id' => 22],
            ['name' => 'Kabupaten Murung Raya', 'slug' => 'kabupaten-murung-raya', 'provinsi_id' => 22],
            ['name' => 'Kabupaten Pulang Pisau', 'slug' => 'kabupaten-pulang-pisau', 'provinsi_id' => 22],
            ['name' => 'Kabupaten Seruyan', 'slug' => 'kabupaten-seruyan', 'provinsi_id' => 22],
            ['name' => 'Kabupaten Sukamara', 'slug' => 'kabupaten-sukamara', 'provinsi_id' => 22],
            ['name' => 'Kota Balikpapan', 'slug' => 'kota-balikpapan', 'provinsi_id' => 23],
            ['name' => 'Kota Bontang', 'slug' => 'kota-bontang', 'provinsi_id' => 23],
            ['name' => 'Kota Samarinda', 'slug' => 'kota-samarinda', 'provinsi_id' => 23],
            ['name' => 'Kabupaten Berau', 'slug' => 'kabupaten-berau', 'provinsi_id' => 23],
            ['name' => 'Kabupaten Kutai Barat', 'slug' => 'kabupaten-kutai-barat', 'provinsi_id' => 23],
            ['name' => 'Kabupaten Kutai Kartanegara', 'slug' => 'kabupaten-kutai-kartanegara', 'provinsi_id' => 23],
            ['name' => 'Kabupaten Kutai Timur', 'slug' => 'kabupaten-kutai-timur', 'provinsi_id' => 23],
            ['name' => 'Kabupaten Mahakam Ulu', 'slug' => 'kabupaten-mahakam-ulu', 'provinsi_id' => 23],
            ['name' => 'Kabupaten Paser', 'slug' => 'kabupaten-paser', 'provinsi_id' => 23],
            ['name' => 'Kabupaten Penajam Paser Utara', 'slug' => 'kabupaten-penajam-paser-utara', 'provinsi_id' => 23],
            ['name' => 'Kota Tarakan', 'slug' => 'kota-tarakan', 'provinsi_id' => 24],
            ['name' => 'Kabupaten Bulungan', 'slug' => 'kabupaten-bulungan', 'provinsi_id' => 24],
            ['name' => 'Kabupaten Malinau', 'slug' => 'kabupaten-malinau', 'provinsi_id' => 24],
            ['name' => 'Kabupaten Nunukan', 'slug' => 'kabupaten-nunukan', 'provinsi_id' => 24],
            ['name' => 'Kabupaten Tana Tidung', 'slug' => 'kabupaten-tana-tidung', 'provinsi_id' => 24],
            ['name' => 'Kota Manado', 'slug' => 'kota-manado', 'provinsi_id' => 25],
            ['name' => 'Kota Bitung', 'slug' => 'kota-bitung', 'provinsi_id' => 25],
            ['name' => 'Kota Tomohon', 'slug' => 'kota-tomohon', 'provinsi_id' => 25],
            ['name' => 'Kota Kotamobagu', 'slug' => 'kota-kotamobagu', 'provinsi_id' => 25],
            ['name' => 'Kabupaten Bolaang Mongondow', 'slug' => 'kabupaten-bolaang-mongondow', 'provinsi_id' => 25],
            ['name' => 'Kabupaten Bolaang Mongondow Selatan', 'slug' => 'kabupaten-bolaang-mongondow-selatan', 'provinsi_id' => 25],
            ['name' => 'Kabupaten Bolaang Mongondow Timur', 'slug' => 'kabupaten-bolaang-mongondow-timur', 'provinsi_id' => 25],
            ['name' => 'Kabupaten Bolaang Mongondow Utara', 'slug' => 'kabupaten-bolaang-mongondow-utara', 'provinsi_id' => 25],
            ['name' => 'Kabupaten Kepulauan Sangihe', 'slug' => 'kabupaten-kepulauan-sangihe', 'provinsi_id' => 25],
            ['name' => 'Kabupaten Kepulauan Siau Tagulandang Biaro', 'slug' => 'kabupaten-kepulauan-siau-tagulandang-biaro', 'provinsi_id' => 25],
            ['name' => 'Kabupaten Kepulauan Talaud', 'slug' => 'kabupaten-kepulauan-talaud', 'provinsi_id' => 25],
            ['name' => 'Kabupaten Minahasa', 'slug' => 'kabupaten-minahasa', 'provinsi_id' => 25],
            ['name' => 'Kabupaten Minahasa Selatan', 'slug' => 'kabupaten-minahasa-selatan', 'provinsi_id' => 25],
            ['name' => 'Kabupaten Minahasa Tenggara', 'slug' => 'kabupaten-minahasa-tenggara', 'provinsi_id' => 25],
            ['name' => 'Kabupaten Minahasa Utara', 'slug' => 'kabupaten-minahasa-utara', 'provinsi_id' => 25],
            ['name' => 'Kota Palu', 'slug' => 'kota-palu', 'provinsi_id' => 26],
            ['name' => 'Kabupaten Banggai', 'slug' => 'kabupaten-banggai', 'provinsi_id' => 26],
            ['name' => 'Kabupaten Banggai Kepulauan', 'slug' => 'kabupaten-banggai-kepulauan', 'provinsi_id' => 26],
            ['name' => 'Kabupaten Banggai Laut', 'slug' => 'kabupaten-banggai-laut', 'provinsi_id' => 26],
            ['name' => 'Kabupaten Buol', 'slug' => 'kabupaten-buol', 'provinsi_id' => 26],
            ['name' => 'Kabupaten Donggala', 'slug' => 'kabupaten-donggala', 'provinsi_id' => 26],
            ['name' => 'Kabupaten Morowali', 'slug' => 'kabupaten-morowali', 'provinsi_id' => 26],
            ['name' => 'Kabupaten Morowali Utara', 'slug' => 'kabupaten-morowali-utara', 'provinsi_id' => 26],
            ['name' => 'Kabupaten Parigi Moutong', 'slug' => 'kabupaten-parigi-moutong', 'provinsi_id' => 26],
            ['name' => 'Kabupaten Poso', 'slug' => 'kabupaten-poso', 'provinsi_id' => 26],
            ['name' => 'Kabupaten Sigi', 'slug' => 'kabupaten-sigi', 'provinsi_id' => 26],
            ['name' => 'Kabupaten Tojo Una-Una', 'slug' => 'kabupaten-tojo-una-una', 'provinsi_id' => 26],
            ['name' => 'Kabupaten Toli-Toli', 'slug' => 'kabupaten-toli-toli', 'provinsi_id' => 26],
            ['name' => 'Kota Makassar', 'slug' => 'kota-makassar', 'provinsi_id' => 27],
            ['name' => 'Kota Palopo', 'slug' => 'kota-palopo', 'provinsi_id' => 27],
            ['name' => 'Kota Parepare', 'slug' => 'kota-parepare', 'provinsi_id' => 27],
            ['name' => 'Kabupaten Bantaeng', 'slug' => 'kabupaten-bantaeng', 'provinsi_id' => 27],
            ['name' => 'Kabupaten Barru', 'slug' => 'kabupaten-barru', 'provinsi_id' => 27],
            ['name' => 'Kabupaten Bone', 'slug' => 'kabupaten-bone', 'provinsi_id' => 27],
            ['name' => 'Kabupaten Bulukumba', 'slug' => 'kabupaten-bulukumba', 'provinsi_id' => 27],
            ['name' => 'Kabupaten Enrekang', 'slug' => 'kabupaten-enrekang', 'provinsi_id' => 27],
            ['name' => 'Kabupaten Gowa', 'slug' => 'kabupaten-gowa', 'provinsi_id' => 27],
            ['name' => 'Kabupaten Jeneponto', 'slug' => 'kabupaten-jeneponto', 'provinsi_id' => 27],
            ['name' => 'Kabupaten Kepulauan Selayar', 'slug' => 'kabupaten-kepulauan-selayar', 'provinsi_id' => 27],
            ['name' => 'Kabupaten Luwu', 'slug' => 'kabupaten-luwu', 'provinsi_id' => 27],
            ['name' => 'Kabupaten Luwu Timur', 'slug' => 'kabupaten-luwu-timur', 'provinsi_id' => 27],
            ['name' => 'Kabupaten Luwu Utara', 'slug' => 'kabupaten-luwu-utara', 'provinsi_id' => 27],
            ['name' => 'Kabupaten Maros', 'slug' => 'kabupaten-maros', 'provinsi_id' => 27],
            ['name' => 'Kabupaten Pangkajene Kepulauan', 'slug' => 'kabupaten-pangkajene-kepulauan', 'provinsi_id' => 27],
            ['name' => 'Kabupaten Pinrang', 'slug' => 'kabupaten-pinrang', 'provinsi_id' => 27],
            ['name' => 'Kabupaten Sidenreng Rappang', 'slug' => 'kabupaten-sidenreng-rappang', 'provinsi_id' => 27],
            ['name' => 'Kabupaten Sinjai', 'slug' => 'kabupaten-sinjai', 'provinsi_id' => 27],
            ['name' => 'Kabupaten Soppeng', 'slug' => 'kabupaten-soppeng', 'provinsi_id' => 27],
            ['name' => 'Kabupaten Takalar', 'slug' => 'kabupaten-takalar', 'provinsi_id' => 27],
            ['name' => 'Kabupaten Tana Toraja', 'slug' => 'kabupaten-tana-toraja', 'provinsi_id' => 27],
            ['name' => 'Kabupaten Toraja Utara', 'slug' => 'kabupaten-toraja-utara', 'provinsi_id' => 27],
            ['name' => 'Kabupaten Wajo', 'slug' => 'kabupaten-wajo', 'provinsi_id' => 27],
            ['name' => 'Kota Baubau', 'slug' => 'kota-baubau', 'provinsi_id' => 28],
            ['name' => 'Kota Kendari', 'slug' => 'kota-kendari', 'provinsi_id' => 28],
            ['name' => 'Kabupaten Bombana', 'slug' => 'kabupaten-bombana', 'provinsi_id' => 28],
            ['name' => 'Kabupaten Buton', 'slug' => 'kabupaten-buton', 'provinsi_id' => 28],
            ['name' => 'Kabupaten Buton Selatan', 'slug' => 'kabupaten-buton-selatan', 'provinsi_id' => 28],
            ['name' => 'Kabupaten Buton Tengah', 'slug' => 'kabupaten-buton-tengah', 'provinsi_id' => 28],
            ['name' => 'Kabupaten Buton Utara', 'slug' => 'kabupaten-buton-utara', 'provinsi_id' => 28],
            ['name' => 'Kabupaten Kolaka', 'slug' => 'kabupaten-kolaka', 'provinsi_id' => 28],
            ['name' => 'Kabupaten Kolaka Timur', 'slug' => 'kabupaten-kolaka-timur', 'provinsi_id' => 28],
            ['name' => 'Kabupaten Kolaka Utara', 'slug' => 'kabupaten-kolaka-utara', 'provinsi_id' => 28],
            ['name' => 'Kabupaten Konawe', 'slug' => 'kabupaten-konawe', 'provinsi_id' => 28],
            ['name' => 'Kabupaten Konawe Kepulauan', 'slug' => 'kabupaten-konawe-kepulauan', 'provinsi_id' => 28],
            ['name' => 'Kabupaten Konawe Selatan', 'slug' => 'kabupaten-konawe-selatan', 'provinsi_id' => 28],
            ['name' => 'Kabupaten Konawe Utara', 'slug' => 'kabupaten-konawe-utara', 'provinsi_id' => 28],
            ['name' => 'Kabupaten Muna', 'slug' => 'kabupaten-muna', 'provinsi_id' => 28],
            ['name' => 'Kabupaten Muna Barat', 'slug' => 'kabupaten-muna-barat', 'provinsi_id' => 28],
            ['name' => 'Kabupaten Wakatobi', 'slug' => 'kabupaten-wakatobi', 'provinsi_id' => 28],
            ['name' => 'Kota Gorontalo', 'slug' => 'kota-gorontalo', 'provinsi_id' => 29],
            ['name' => 'Kabupaten Boalemo', 'slug' => 'kabupaten-boalemo', 'provinsi_id' => 29],
            ['name' => 'Kabupaten Bone Bolango', 'slug' => 'kabupaten-bone-bolango', 'provinsi_id' => 29],
            ['name' => 'Kabupaten Gorontalo', 'slug' => 'kabupaten-gorontalo', 'provinsi_id' => 29],
            ['name' => 'Kabupaten Gorontalo Utara', 'slug' => 'kabupaten-gorontalo-utara', 'provinsi_id' => 29],
            ['name' => 'Kabupaten Pohuwato', 'slug' => 'kabupaten-pohuwato', 'provinsi_id' => 29],
            ['name' => 'Kabupaten Majene', 'slug' => 'kabupaten-majene', 'provinsi_id' => 30],
            ['name' => 'Kabupaten Mamasa', 'slug' => 'kabupaten-mamasa', 'provinsi_id' => 30],
            ['name' => 'Kabupaten Mamuju', 'slug' => 'kabupaten-mamuju', 'provinsi_id' => 30],
            ['name' => 'Kabupaten Mamuju Tengah', 'slug' => 'kabupaten-mamuju-tengah', 'provinsi_id' => 30],
            ['name' => 'Kabupaten Polewali Mandar', 'slug' => 'kabupaten-polewali-mandar', 'provinsi_id' => 30],
            ['name' => 'Kabupaten Pasangkayu', 'slug' => 'kabupaten-pasangkayu', 'provinsi_id' => 30],
            ['name' => 'Kota Ambon', 'slug' => 'kota-ambon', 'provinsi_id' => 31],
            ['name' => 'Kota Tual', 'slug' => 'kota-tual', 'provinsi_id' => 31],
            ['name' => 'Kabupaten Buru', 'slug' => 'kabupaten-buru', 'provinsi_id' => 31],
            ['name' => 'Kabupaten Buru Selatan', 'slug' => 'kabupaten-buru-selatan', 'provinsi_id' => 31],
            ['name' => 'Kabupaten Kepulauan Aru', 'slug' => 'kabupaten-kepulauan-aru', 'provinsi_id' => 31],
            ['name' => 'Kabupaten Kepulauan Tanimbar', 'slug' => 'kabupaten-kepulauan-tanimbar', 'provinsi_id' => 31],
            ['name' => 'Kabupaten Maluku Barat Daya', 'slug' => 'kabupaten-maluku-barat-daya', 'provinsi_id' => 31],
            ['name' => 'Kabupaten Maluku Tengah', 'slug' => 'kabupaten-maluku-tengah', 'provinsi_id' => 31],
            ['name' => 'Kabupaten Maluku Tenggara', 'slug' => 'kabupaten-maluku-tenggara', 'provinsi_id' => 31],
            ['name' => 'Kabupaten Seram Bagian Barat', 'slug' => 'kabupaten-seram-bagian-barat', 'provinsi_id' => 31],
            ['name' => 'Kabupaten Seram Bagian Timur', 'slug' => 'kabupaten-seram-bagian-timur', 'provinsi_id' => 31],
            ['name' => 'Kota Ternate', 'slug' => 'kota-ternate', 'provinsi_id' => 32],
            ['name' => 'Kota Tidore Kepulauan', 'slug' => 'kota-tidore-kepulauan', 'provinsi_id' => 32],
            ['name' => 'Kabupaten Halmahera Barat', 'slug' => 'kabupaten-halmahera-barat', 'provinsi_id' => 32],
            ['name' => 'Kabupaten Halmahera Tengah', 'slug' => 'kabupaten-halmahera-tengah', 'provinsi_id' => 32],
            ['name' => 'Kabupaten Halmahera Timur', 'slug' => 'kabupaten-halmahera-timur', 'provinsi_id' => 32],
            ['name' => 'Kabupaten Halmahera Utara', 'slug' => 'kabupaten-halmahera-utara', 'provinsi_id' => 32],
            ['name' => 'Kabupaten Halmahera Selatan', 'slug' => 'kabupaten-halmahera-selatan', 'provinsi_id' => 32],
            ['name' => 'Kabupaten Kepulauan Sula', 'slug' => 'kabupaten-kepulauan-sula', 'provinsi_id' => 32],
            ['name' => 'Kabupaten Pulau Morotai', 'slug' => 'kabupaten-pulau-morotai', 'provinsi_id' => 32],
            ['name' => 'Kabupaten Pulau Taliabu', 'slug' => 'kabupaten-pulau-taliabu', 'provinsi_id' => 32],
            ['name' => 'Kabupaten Biak Numfor', 'slug' => 'kabupaten-biak-numfor', 'provinsi_id' => 33],
            ['name' => 'Kabupaten Jayapura', 'slug' => 'kabupaten-jayapura', 'provinsi_id' => 33],
            ['name' => 'Kabupaten Keerom', 'slug' => 'kabupaten-keerom', 'provinsi_id' => 33],
            ['name' => 'Kabupaten Kepulauan Yapen', 'slug' => 'kabupaten-kepulauan-yapen', 'provinsi_id' => 33],
            ['name' => 'Kabupaten Mamberamo Raya', 'slug' => 'kabupaten-mamberamo-raya', 'provinsi_id' => 33],
            ['name' => 'Kabupaten Sarmi', 'slug' => 'kabupaten-sarmi', 'provinsi_id' => 33],
            ['name' => 'Kabupaten Supiori', 'slug' => 'kabupaten-supiori', 'provinsi_id' => 33],
            ['name' => 'Kabupaten Waropen', 'slug' => 'kabupaten-waropen', 'provinsi_id' => 33],
            ['name' => 'Kota Jayapura', 'slug' => 'kota-jayapura', 'provinsi_id' => 33],
            ['name' => 'Kabupaten Fakfak', 'slug' => 'kabupaten-fakfak', 'provinsi_id' => 34],
            ['name' => 'Kabupaten Kaimana', 'slug' => 'kabupaten-kaimana', 'provinsi_id' => 34],
            ['name' => 'Kabupaten Manokwari', 'slug' => 'kabupaten-manokwari', 'provinsi_id' => 34],
            ['name' => 'Kabupaten Manokwari Selatan', 'slug' => 'kabupaten-manokwari-selatan', 'provinsi_id' => 34],
            ['name' => 'Kabupaten Pegunungan Arfak', 'slug' => 'kabupaten-pegunungan-arfak', 'provinsi_id' => 34],
            ['name' => 'Kabupaten Teluk Bintuni', 'slug' => 'kabupaten-teluk-bintuni', 'provinsi_id' => 34],
            ['name' => 'Kabupaten Teluk Wondama', 'slug' => 'kabupaten-teluk-wondama', 'provinsi_id' => 34],
            ['name' => 'Kabupaten Maybrat', 'slug' => 'kabupaten-maybrat', 'provinsi_id' => 35],
            ['name' => 'Kabupaten Raja Ampat', 'slug' => 'kabupaten-raja-ampat', 'provinsi_id' => 35],
            ['name' => 'Kabupaten Sorong', 'slug' => 'kabupaten-sorong', 'provinsi_id' => 35],
            ['name' => 'Kabupaten Sorong Selatan', 'slug' => 'kabupaten-sorong-selatan', 'provinsi_id' => 35],
            ['name' => 'Kabupaten Tambrauw', 'slug' => 'kabupaten-tambrauw', 'provinsi_id' => 35],
            ['name' => 'Kota Sorong', 'slug' => 'kota-sorong', 'provinsi_id' => 35],
            ['name' => 'Kabupaten Jayawijaya', 'slug' => 'kabupaten-jayawijaya', 'provinsi_id' => 36],
            ['name' => 'Kabupaten Lanny Jaya', 'slug' => 'kabupaten-lanny-jaya', 'provinsi_id' => 36],
            ['name' => 'Kabupaten Mamberamo Tengah', 'slug' => 'kabupaten-mamberamo-tengah', 'provinsi_id' => 36],
            ['name' => 'Kabupaten Nduga', 'slug' => 'kabupaten-nduga', 'provinsi_id' => 36],
            ['name' => 'Kabupaten Pegunungan Bintang', 'slug' => 'kabupaten-pegunungan-bintang', 'provinsi_id' => 36],
            ['name' => 'Kabupaten Tolikara', 'slug' => 'kabupaten-tolikara', 'provinsi_id' => 36],
            ['name' => 'Kabupaten Yalimo', 'slug' => 'kabupaten-yalimo', 'provinsi_id' => 36],
            ['name' => 'Kabupaten Yahukimo', 'slug' => 'kabupaten-yahukimo', 'provinsi_id' => 36],
            ['name' => 'Kabupaten Asmat', 'slug' => 'kabupaten-asmat', 'provinsi_id' => 37],
            ['name' => 'Kabupaten Boven Digoel', 'slug' => 'kabupaten-boven-digoel', 'provinsi_id' => 37],
            ['name' => 'Kabupaten Mappi', 'slug' => 'kabupaten-mappi', 'provinsi_id' => 37],
            ['name' => 'Kabupaten Merauke', 'slug' => 'kabupaten-merauke', 'provinsi_id' => 37],
            ['name' => 'Kabupaten Deiyai', 'slug' => 'kabupaten-deiyai', 'provinsi_id' => 38],
            ['name' => 'Kabupaten Dogiyai', 'slug' => 'kabupaten-dogiyai', 'provinsi_id' => 38],
            ['name' => 'Kabupaten Intan Jaya', 'slug' => 'kabupaten-intan-jaya', 'provinsi_id' => 38],
            ['name' => 'Kabupaten Mimika', 'slug' => 'kabupaten-mimika', 'provinsi_id' => 38],
            ['name' => 'Kabupaten Nabire', 'slug' => 'kabupaten-nabire', 'provinsi_id' => 38],
            ['name' => 'Kabupaten Paniai', 'slug' => 'kabupaten-paniai', 'provinsi_id' => 38],
            ['name' => 'Kabupaten Puncak', 'slug' => 'kabupaten-puncak', 'provinsi_id' => 38],
            ['name' => 'Kabupaten Puncak Jaya', 'slug' => 'kabupaten-puncak-jaya', 'provinsi_id' => 38],
        ];
        DB::table('kotas')->insert($data);    
    }
}
